const OK_STATUS = 200;
const OK_CREATED = 201;

const ERROR_INCORRECT_DATA = 400;
const ERROR_UNAUTHORIZED = 401;
const ERROR_FORBIDDEN = 403;
const ERROR_NOT_FOUND = 404;
const ERROR_CONFLICT = 409;
const ERROR_INTERNAL_SERVER = 500;

module.exports = {
  OK_STATUS,
  OK_CREATED,
  ERROR_INCORRECT_DATA,
  ERROR_NOT_FOUND,
  ERROR_INTERNAL_SERVER,
  ERROR_FORBIDDEN,
  ERROR_UNAUTHORIZED,
  ERROR_CONFLICT,
};
